version: '3'

services:
  restapi:
    build: ./api
    ports:
      - 5879:5000

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5878:80
    depends_on:
      - restapi
    environment:
      BACKEND_ADDR: restapi
      BACKEND_PORT: 5000
